cropper:
  cropR: 0.3
  cropZ: 1.0
  ladC: 0
  ladW: 6000
  mesh: 0.001
picker:
  azimuth:
    max: 1
    min: 0
  fitness:
    max: 1
    min: 0.7
rovi:
  live:
    camera:
      ExposureTime: 300000
      Gain: 63
  pshift_genpc:
    camera:
      ExposureTime: 8400
      Gain: 0
    projector:
      Intencity: 150
      Mode: 1
searcher:
  distance_threshold: 0.1
  feature_max_nn: 100
  feature_radius: 0.03
  icp_threshold: 0.005
  normal_max_nn: 30
  normal_radius: 0.01
